// Run with: node tests/session-files.browser.mjs (requires Playwright Chromium).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'vite';
import { chromium } from 'playwright';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
const pause = ms => new Promise(r => setTimeout(r, ms));

test('session file UI: folder navigation, safe previews, scoped requests and async switches', async () => {
  const server = await createServer({ root, configFile: root + 'vite.config.ts', server: { port: 0, host: '127.0.0.1' } });
  await server.listen();
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  const requests = [], errors = [];
  let slow = false, rejectLists = false, restored = false;
  const creations = [], releaseCreates = [];
  const conversations = [{ conversation_id: 'B', title: 'Existing session B', owner_email: 'me@example.com', created_at: Date.now() }];
  page.on('pageerror', e => errors.push(e.message));
  await page.route('**/api/**', async route => {
    const req = route.request(), url = new URL(req.url());
    const body = req.postDataJSON() || {};
    requests.push({ path: url.pathname, body, query: Object.fromEntries(url.searchParams) });
    if (slow && body.conversation_id === 'A' && url.pathname.endsWith('/file/list')) await pause(180);
    if (rejectLists && url.pathname.endsWith('/file/list')) return route.fulfill({ status: 500, json: { code: 500, msg: 'test error' } });
    if (url.pathname.endsWith('/conversation/create-conversation')) {
      const conversation = { conversation_id: `created-${creations.length}`, title: 'New chat', owner_email: 'me@example.com', created_at: Date.now() };
      creations.push(conversation);
      await new Promise(resolve => releaseCreates.push(resolve));
      conversations.push(conversation);
      return route.fulfill({ json: { code: 0, data: conversation } });
    }
    if (url.pathname.endsWith('/events')) return route.fulfill({ status: 503, body: '' });
    if (url.pathname.endsWith('/chat/run')) return route.fulfill({ contentType: 'text/event-stream', body: 'data: {"type":"done"}\n\n' });
    if (url.pathname.endsWith('/file/download')) {
      const name = url.searchParams.get('path');
      if (name === 'many-lines.txt') return route.fulfill({ body: '\n'.repeat(120_000) });
      if (name === 'slow.txt') { await pause(180); return route.fulfill({ body: 'OLD PREVIEW' }); }
      if (name === 'large.csv') return route.fulfill({ body: Array.from({ length: 240 }, () => Array.from({ length: 35 }, () => 'cell').join(',')).join('\n') });
      if (name.endsWith('.js')) return route.fulfill({ body: 'const html = "<img src=x onerror=alert(1)>"; // safe\nreturn 42;' });
      if (name.endsWith('.csv')) return route.fulfill({ body: restored ? 'name,note\nrestored,old' : 'name,note,last\r\n"a,b","line 1\r\nline ""2""",\r\n' });
      return route.fulfill({ body: 'plain text' });
    }
    let data = {};
    if (url.pathname.endsWith('/auth/me')) data = { email: 'me@example.com', name: 'Test' };
    if (url.pathname.endsWith('/conversation/list')) data = conversations;
    if (url.pathname.endsWith('/conversation/shared-with-me') || url.pathname.endsWith('/conversation/get-messages') || url.pathname.endsWith('/models')) data = [];
    if (url.pathname.endsWith('/run/list')) data = { runs: [] };
    if (url.pathname.endsWith('/file/list')) data = body.conversation_id === 'B' ? [{ name: 'B-only.txt', dir: false, size: 4 }] : body.conversation_id === 'empty' ? [] : body.path === '.' ? [{ name: 'a', dir: true, size: 0 }, { name: 'A-only.txt', dir: false, size: 4 }] : body.path === 'a' ? [{ name: 'b', dir: true, size: 0 }] : [{ name: 'sample.csv', dir: false, size: 60 }];
    if (url.pathname.endsWith('/file/versions')) data = [{ ts: 'old', when: 1000, size: 10, path: '.versions/old/sample.csv' }];
    if (url.pathname.endsWith('/file/restore')) restored = true;
    if (url.pathname.endsWith('/artifacts/list')) data = { artifacts: [] };
    if (url.pathname.endsWith('/skill/list')) data = { skills: [] };
    await route.fulfill({ json: { code: 0, data } });
  });
  const set = async state => { await page.evaluate(s => window.fileTest.set(s), state); await pause(40); };
  try {
    await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/tests/session-files.html`);
    await page.waitForFunction(() => !!window.fileTest);
    await pause(100);
    assert.equal(requests.filter(r => r.path.includes('/file/')).length, 0, 'overview does not query files without a conversation');
    await set({ tab: 'files' });
    await page.getByText('请选择会话', { exact: true }).waitFor();
    assert.equal(requests.filter(r => r.path.includes('/file/')).length, 0);
    await set({ conversationID: 'empty' });
    await page.getByText('工作区还是空的', { exact: true }).waitFor();
    await set({ conversationID: 'A' });
    await page.getByRole('button', { name: 'a', exact: true }).click();
    await page.getByRole('button', { name: 'b', exact: true }).click();
    await page.getByRole('button', { name: 'sample.csv', exact: true }).click();
    const dialog = page.getByRole('dialog');
    await dialog.getByRole('cell', { name: 'a,b', exact: true }).waitFor();
    assert.equal(await dialog.locator('tbody td').nth(1).textContent(), 'line 1\r\nline "2"');
    assert.equal(await dialog.locator('tbody td').nth(2).textContent(), '');
    const download = new URL(await dialog.getByRole('link', { name: '下载', exact: true }).getAttribute('href'), page.url());
    assert.equal(download.searchParams.get('conv'), 'A'); assert.equal(download.searchParams.get('path'), 'a/b/sample.csv');
    await dialog.getByTitle('版本历史').click();
    await dialog.getByRole('button', { name: /1\/1/ }).click();
    await dialog.getByRole('button', { name: /恢复此版本/ }).click();
    await dialog.getByRole('cell', { name: 'restored', exact: true }).waitFor();
    assert.ok(requests.some(r => r.path.endsWith('/file/restore') && r.body.conversation_id === 'A' && r.body.path === 'a/b/sample.csv'));
    await dialog.getByRole('button', { name: '关闭预览' }).click();
    await page.locator('input[type=file]').setInputFiles({ name: 'upload.txt', mimeType: 'text/plain', buffer: Buffer.from('test') });
    await pause(100);
    assert.ok(requests.some(r => r.path.endsWith('/file/upload-chunk') && r.body.filename === 'a/b/upload.txt' && r.body.conversation_id === 'A'));
    await page.getByRole('button', { name: '删除 sample.csv', exact: true }).click();
    await pause(80);
    assert.ok(requests.some(r => r.path.endsWith('/file/delete') && r.body.path === 'a/b/sample.csv' && r.body.conversation_id === 'A'));
    await page.getByRole('button', { name: '← 返回上级', exact: true }).click();
    await page.getByRole('button', { name: 'b', exact: true }).waitFor();
    await page.getByRole('button', { name: '← 返回上级', exact: true }).click();
    await page.getByRole('button', { name: 'A-only.txt', exact: true }).waitFor();
    slow = true;
    await page.getByRole('button', { name: 'a', exact: true }).click();
    await set({ conversationID: 'B' }); await pause(220);
    await page.getByRole('button', { name: 'B-only.txt', exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: 'b', exact: true }).count(), 0);
    assert.equal(await page.getByRole('button', { name: '← 返回上级', exact: true }).count(), 0);
    slow = false;
    await page.getByRole('button', { name: 'B-only.txt', exact: true }).click();
    await dialog.waitFor();
    await set({ conversationID: 'A' });
    assert.equal(await dialog.count(), 0);
    await set({ mode: 'preview', conversationID: 'A', name: 'unsafe.js' });
    await dialog.locator('code').waitFor();
    await page.waitForFunction(() => document.querySelector('code')?.textContent.includes('const html'));
    assert.equal(await dialog.locator('img').count(), 0);
    assert.equal(await dialog.locator('code .font-semibold').first().textContent(), 'const');
    await set({ name: 'large.csv' });
    await dialog.getByRole('table').waitFor();
    assert.equal(await dialog.locator('tbody tr').count(), 200);
    assert.equal(await dialog.locator('thead th').count(), 30);
    await dialog.getByText(/表格预览已截断/).waitFor();
    if (process.env.ORKA_UI_SCREENSHOT) await page.screenshot({ path: process.env.ORKA_UI_SCREENSHOT });
    await set({ name: 'many-lines.txt' });
    await dialog.getByText(/预览已截断：最多读取/).waitFor();
    await dialog.getByTitle('版本历史').click();
    await dialog.getByRole('button', { name: /1\/1/ }).click();
    await dialog.getByText(/差异预览已截断/).waitFor();
    await set({ name: 'slow.txt' });
    await set({ name: 'fast.txt', conversationID: 'B' });
    await dialog.locator('code').waitFor();
    await pause(220);
    assert.equal(await dialog.locator('code').textContent(), 'plain text');
    await set({ mode: 'thread', conversationID: 'A', shared: false });
    await page.getByText('📎 本会话文件 · 1', { exact: true }).waitFor();
    await page.getByRole('button', { name: /sample.csv/ }).last().click();
    await dialog.waitFor();
    assert.ok(requests.some(r => r.path.endsWith('/file/list') && r.body.path === 'a/b' && r.body.conversation_id === 'A'));
    await set({ conversationID: 'B' }); assert.equal(await dialog.count(), 0);
    await set({ conversationID: 'A', shared: true });
    await page.getByText('📎 本会话文件 · 1', { exact: true }).waitFor();
    await page.getByRole('button', { name: /sample.csv/ }).last().click();
    await dialog.waitFor();
    assert.equal(await dialog.getByTitle('版本历史').count(), 0);
    await set({ mode: 'composer', conversationID: 'A' });
    await page.locator('textarea').fill('@');
    await page.locator('textarea').press('ArrowRight');
    await page.getByText('A-only.txt', { exact: true }).waitFor();
    await set({ conversationID: 'B' });
    await page.getByText('B-only.txt', { exact: true }).waitFor();
    assert.equal(await page.getByText('A-only.txt', { exact: true }).count(), 0);
    rejectLists = true;
    await set({ conversationID: 'A' }); await pause(200);
    assert.deepEqual(errors, [], 'list failures are caught');
    rejectLists = false;
    await set({ conversationID: '' });
    const upload = page.locator('input[type=file]');
    await upload.setInputFiles({ name: 'one.txt', mimeType: 'text/plain', buffer: Buffer.from('1') });
    await upload.setInputFiles({ name: 'two.txt', mimeType: 'text/plain', buffer: Buffer.from('2') });
    await page.getByRole('button', { name: '移除 one.txt' }).waitFor();
    await page.getByRole('button', { name: '移除 two.txt' }).waitFor();
    assert.equal(await page.getByTestId('creates').textContent(), '1');
    assert.equal(requests.filter(r => r.path.endsWith('/file/upload-chunk') && ['one.txt','two.txt'].includes(r.body.filename) && r.body.conversation_id === 'new').length, 2);
    await set({ conversationID: 'B' });
    assert.equal(await page.getByRole('button', { name: '移除 one.txt' }).count(), 0);
    assert.deepEqual(errors, []);
    // Exercise the actual App callback: concurrent initial sends share creation.
    await page.evaluate(() => localStorage.setItem('orka.token', 'test-token'));
    await set({ mode: 'app' });
    const textarea = page.locator('textarea');
    await textarea.waitFor();
    await textarea.fill('first message'); await textarea.press('Enter');
    await textarea.fill('second message'); await textarea.press('Enter');
    await pause(80);
    assert.equal(creations.length, 1, 'App deduplicates initial conversation creation');
    releaseCreates.shift()();
    await page.waitForResponse(r => r.url().endsWith('/chat/run'));
    await pause(100);
    assert.ok(requests.filter(r => r.path.endsWith('/chat/run')).every(r => r.body.conversation_id === 'created-0'));
    await page.getByRole('button', { name: '+ New chat', exact: true }).click();
    await page.locator('input[type=file]').setInputFiles([
      { name: 'late-one.txt', mimeType: 'text/plain', buffer: Buffer.from('1') },
      { name: 'late-two.txt', mimeType: 'text/plain', buffer: Buffer.from('2') },
    ]);
    await pause(60);
    assert.equal(creations.length, 2);
    await page.getByText('Existing session B', { exact: true }).first().click();
    releaseCreates.shift()(); await pause(180);
    assert.equal(await page.getByRole('button', { name: '移除 late-one.txt' }).count(), 0);
    assert.equal(requests.filter(r => r.path.endsWith('/file/upload-chunk') && r.body.filename.startsWith('late-')).length, 0);
    await textarea.fill('@'); await textarea.press('ArrowRight');
    await page.getByText('B-only.txt', { exact: true }).waitFor();
    await page.getByRole('button', { name: '+ New chat', exact: true }).click();
    await page.locator('input[type=file]').setInputFiles([
      { name: 'new-one.txt', mimeType: 'text/plain', buffer: Buffer.from('1') },
      { name: 'new-two.txt', mimeType: 'text/plain', buffer: Buffer.from('2') },
    ]);
    await pause(60);
    assert.equal(creations.length, 3);
    releaseCreates.shift()();
    await page.getByRole('button', { name: '移除 new-one.txt' }).waitFor();
    await page.getByRole('button', { name: '移除 new-two.txt' }).waitFor();
    await textarea.fill('use my files'); await textarea.press('Enter');
    await pause(100);
    const sent = requests.find(r => r.path.endsWith('/chat/run') && r.body.message === 'use my files');
    assert.equal(sent.body.conversation_id, 'created-2');
    assert.deepEqual(sent.body.file_ids, ['new-one.txt', 'new-two.txt']);
    assert.deepEqual(errors, []);
    for (const r of requests.filter(r => r.path.includes('/file/'))) assert.ok(r.body.conversation_id || r.query.conv, `${r.path} must have a conversation`);
  } finally { await browser.close(); await server.close(); }
});
