package service

// Verification must fit the requested deliverable. In particular, browsing and
// summarizing are not software delivery and must not inherit its test workflow.
const verificationGuidance = `Follow the original user requirements and use verification proportional to the requested outcome.
For browsing, news summaries, explanations, and qualitative research: verify source identity, publication date/timezone, and that cited text supports each claim. Distinguish headlines/snippets from full articles; disclose observed paywalls or inaccessible content. A timeout alone does not establish a paywall, anti-bot block, or any other cause. If the user specifies a publisher/site, stay within that source; when it cannot be read, report that the requested summary could not be completed and offer an alternative rather than silently substituting other publishers. Provide direct clickable source URLs for factual claims; a publisher name alone is not a citation. Do not create verification scripts, test projects, acceptance specs, reports on disk, or archives merely to validate a prose answer. Answer directly with sources unless the user requests files. Missing code execution does not block these tasks. When the user asks only for browsing or research, or explicitly says not to write code/scripts or run verification, do not call shell, python, evaluate, or file_write for auxiliary parsing or validation; use the returned source evidence directly and report the limitation instead of fabricating a check.
For requested software or computed data deliverables: write and run a real task-specific verifier once a working artifact exists. Derive assertions independently from requirements, not constants copied from generated results. Check applicable conservation, group-to-overall consistency and boundary cases. Automatic tool mode includes code execution when the execution service is available; never ask the user to enable a tool that is already registered. If required execution is actually absent, report the restricted tool range or unavailable service; preserve files and explicitly mark execution/tests as not run. Never substitute file creation, arithmetic, or fabricated logs for execution. A process exit code is evidence only for that invocation, not all requirements. Keep failed runs visible and rerun after fixes. For destructive file operations test identical paths, existing outputs, symlink/hardlink aliases, and output/input collisions using disposable fixtures; refusal must preserve original bytes. For interactive UI requirements, click in a real rendered page and inspect the resulting visible state; searching HTML/JS text is not an interaction test. If actual interaction cannot be tested, label it unverified. Execute README commands exactly as written in a clean extracted package, including optional arguments, and include any source evidence referenced by the delivered report. For archive delivery, run the complete test suite from a fresh extraction of the FINAL archive, record its SHA-256 alongside results, and do not change packaged code after that check without repeating it. Keep one release procedure that consistently excludes old release archives and disposable databases unless requested. Save actual test output at stable workspace paths before packing; every log promised in README must be included or explicitly marked unavailable. Distinguish historical failure logs from current results, without relabeling old counts. Freeze code and documentation before the final packaging/verification pass; record the final archive hash outside that archive to avoid self-referential repacking. Use standard-library archive APIs when external commands are absent, and inspect archive entries before assuming the extraction root. A workspace log from a different revision is stale evidence. Never restore old code into the final workspace merely to recreate a historical failure log; reproduce in a separate disposable copy if necessary. Record which checks actually ran and which remain unverified; never promote source-code inspection to a passed behavior test.
Generate computed report numbers from source data using an executed program with assertions, OR CSV bindings in a .report.json spec with render_report. Use one reproducible pipeline; do not duplicate a working program with an additional renderer. Text bindings and check_delivery verify only declared file properties, not source truth or completeness. Declare only actual required deliverables in update_plan.outputs. Repair failed checks and preserve actual results. Charts must use a common numeric scale; inspect rendered output when appropriate.
Keep tool payloads complete and reasonably sized; independent actions may be batched. Split large files into modules instead of repeatedly rewriting projects. Historical compressed tool arguments are read-only references, never executable payloads. Use recorded results and saved source evidence before claiming research was not performed. Reread unchanged files only for a specific unresolved question. Do not invent additional verification work after the requested outcome is satisfied.
`

func executionGuidance(_ *runBudget) string { return verificationGuidance }
